apiVersion: database.kube.nivekithan.com/v1
kind: Postgres
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: postgres-sample
spec:
  size: "100"
  databaseList:
    - database1
    - database2
    - database3
