---
apiVersion: v1
kind: Namespace
metadata:
  name: inital
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inital-deploy
  namespace: inital
  labels:
    app: inital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inital
  template:
    spec:
      containers:
        - name: inital
          image: crccheck/hello-world
          ports:
            - name: inital-port
              containerPort: 8000

    metadata:
      labels:
        app: inital
---
apiVersion: v1
kind: Service
metadata:
  name: inital-service
  namespace: inital
  labels:
    app: inital
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: inital-port
  selector:
    app: inital
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inital-ingress
  namespace: inital
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-entry-point: websecure
    traefik.ingress.kubernetes.io/redirect-permanent: "false"
    cert-manager.io/issuer: initial-tls-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - kube.nivekithan.com
      secretName: initial-tls-secret
  rules:
    - host: kube.nivekithan.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inital-service
                port:
                  number: 80

---
# Issuer for letsencrypt
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: initial-tls-issuer
  namespace: inital
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: nivekithan363@gmail.com
    # The ACME certificate profile
    profile: tlsserver
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: initial-tls-private-key
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
