---
apiVersion: v1
kind: Namespace
metadata:
  name: inital
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inital-deploy
  namespace: inital
  labels:
    app: inital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inital
  template:
    spec:
      containers:
        - name: inital
          image: crccheck/hello-world
          ports:
            - name: inital-port
              containerPort: 8000

    metadata:
      labels:
        app: inital
---
apiVersion: v1
kind: Service
metadata:
  name: inital-service
  namespace: inital
  labels:
    app: inital
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: inital-port
  selector:
    app: inital
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inital-ingress
  namespace: inital
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inital-service
                port:
                  number: 80
