[my-pg-database]
 pg1-path=/var/lib/postgresql/data

[global]
start-fast=y
repo1-bundle=y
repo1-type=s3
repo1-s3-bucket=$S3_BUCKET_NAME
repo1-s3-endpoint=$S3_ENDPOINT
repo1-s3-key=$S3_ACCESS_KEY
repo1-s3-key-secret=$S3_ACCESS_KEY_SECRET
repo1-s3-region=$S3_REGION
repo1-retention-full=2

[global:archive-push]
compress-level=3
